name: Push commit
on: 
  push:
    branches:
      - main
permissions:
  contents: write
  
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        ref: ${{ github.head_ref }}
    - uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Recommit
